# set prefix
set -g prefix C-a

set -g base-index 1
set -g pane-base-index 1

set -g status-bg black


set-option -g terminal-features 'xterm-256color:RGB'

# mouse support
set -g mouse on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# style
primary="#FF7518"
status_right_bg="#1c232d"
set -g status-position top
set -g status-style "fg=#{primary},bg=default"
set -g status-left '🔥 '
set -g status-right " #S 🎯"
set -g status-right-style 'fg=white,bg=#{status_right_bg}'
setw -g window-status-format ' #I:#W '
setw -g window-status-current-format ' #I:#W '
setw -g window-status-style "fg=white,bg=default"
setw -g window-status-current-style "fg=black,bg=#{primary}"
set-option -g pane-border-style 'fg=#{primary}'
set-option -g pane-active-border-style 'fg=#{primary}'

# KEYBINDS
# reload with Prefix + r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Tmux config reloaded!"

# Dispaly popups
bind y display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "yazi"
bind p display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "podman-tui"

# Pane actions
bind-key -n C-p switch-client -T panekeys 
bind-key -T panekeys x confirm-before -p "Close pane? (y/n)?" kill-pane
bind-key -T panekeys h select-pane -L
bind-key -T panekeys j select-pane -D
bind-key -T panekeys k select-pane -U
bind-key -T panekeys l select-pane -R

# Tab actions
bind-key -n C-t switch-client -T tabkeys
bind-key -T tabkeys n new-window -c "#{pane_current_path}"
bind-key -T tabkeys x confirm-before -p "Close tindow? (y/n)?" kill-window
bind-key -T tabkeys r command-prompt -I "#W" "rename-window '%%'"
bind-key -T tabkeys p split-window -h -c "#{pane_current_path}"
bind-key -T tabkeys h split-window -h -c "#{pane_current_path}"
bind-key -T tabkeys v split-window -v -c "#{pane_current_path}"
bind-key -n M-l next-window
bind-key -n M-h previous-window

# session
bind-key -n C-s switch-client -T sessionkeys
bind-key -T sessionkeys r command-prompt -I "#S" "rename-session '%%'"
bind-key -T sessionkeys d detach-client

# open hop session manager
bind-key o display-popup -E -w 35%  "hop"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '$HOME/.config/tmux/plugins/tpm/tpm'
